import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home({ text }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>{text}</div>
      </main>
    </div>
  )
}

export const getStaticProps = async () => {
  return {
    props: {
      text: 'Some plain text & an ampersand!',
    },
    revalidate: 600,
  };
};
